### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by huchenhai** [IBM-Cloud/clouddatabases-helloworld-kubernetes-examples#1]
Hi, I'm using knex.js  with pg, getting such error this is my config:
`
  var pg = require('pg');

  pg.defaults.ssl =  {
    ca: db.connection.postgres.certificate.certificate_base64,
    rejectUnauthorized: true
  }

  //pg.defaults.ssl = true;
  var knex = require('knex')({
    client: 'postgres',
    connection: db.connection.postgres.composed[0]
  });
`

Code works when I turn rejectUnauthorized:flase,  or simply set pg.defaults.ssl = true(without providing base64 ca);
Is it safe to set like this? Wondering why connection works without providing SSL certificate

**Comment by drpalaric** [comment]
It will connect without providing an TLS cert because that's how PG works. The TLS cert only makes sure that the client you're using is connecting to the correct server. I have no idea what `knex` is and IBM doesn't support it.
