### ISSUE TITLE
Can't Clone The Repo With Given Command.

### ISSUE THREAD

**Issue by sudoalgorithm** [IBM-Cloud/clouddatabases-helloworld-kubernetes-examples#6]
Trying to clone the repo using the command listed in the README. It doesn't work, permission issue error.
<img width="1920" alt="Screen Shot 2019-04-03 at 11 20 56 AM" src="https://user-images.githubusercontent.com/13744705/55460270-a20a0600-5602-11e9-86cb-7218adeeb084.png">
You might wanna change the endpoint to HTTPS instead of SSH.

**Comment by aa7955** [comment]
You can select HTTPS from the "Clone or download" button and use that to replace that url:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/6264696/55973776-195f1b80-5c3b-11e9-90c0-993eea7d6ee9.png">

**Comment by emeloibmco** [comment]
i want to use this hello-world, i already downloaded it, but this git only has README.md.   Could you guide me to dowload the helloworld, code?

**Comment by aa7955** [comment]
@emeloibmco 

From the README:
> Clone the repository of the language that you want to use. For instance, you can clone the Node repository by clicking on the Node branch.

<img width="470" alt="Screen Shot 2019-07-22 at 2 07 44 PM" src="https://user-images.githubusercontent.com/6264696/61665580-34a1e400-ac8a-11e9-854f-4c82b5d64a2f.png">
